# Generated by Django 3.2.6 on 2021-11-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.PositiveSmallIntegerField(default=0, verbose_name='Доля пользователя в заказе')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время присоединения к заказу')),
            ],
            options={
                'verbose_name': 'Заказ пользователя',
                'verbose_name_plural': 'Заказы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='manufacturers/', verbose_name='Логотип')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField(default=0, verbose_name='Количество единиц товара в заказе')),
                ('unit_price', models.PositiveIntegerField(default=0, help_text='Сумма в рублях', verbose_name='Цена за единицу товара')),
                ('price', models.PositiveIntegerField(default=0, help_text='Сумма в рублях', verbose_name='Стоимость заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_amass', models.DateTimeField(blank=True, null=True, verbose_name='Время заполнения')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('number_finished', models.PositiveSmallIntegerField(default=0, verbose_name='Завершено заказов такого же товара в таком же количестве')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=10, help_text='Число от 1 до 10', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about_vendor', models.TextField(blank=True, default='', max_length=5000, verbose_name='Отзыв о поставщике')),
                ('text_about_creator', models.TextField(blank=True, default='', max_length=5000, verbose_name='Отзыв о создателе заказа')),
                ('text_about_product', models.TextField(blank=True, default='', max_length=5000, verbose_name='Отзыв о продукте')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='vendors/', verbose_name='Логотип')),
                ('finished_orders', models.PositiveSmallIntegerField(default=0, verbose_name='Завершенные заказы')),
                ('contact_phone', models.CharField(default='', max_length=12, null=True, verbose_name='Номер телефона')),
                ('contact_site', models.CharField(default='', max_length=50, null=True, verbose_name='Сайт')),
                ('contact_social', models.CharField(max_length=200, null=True, verbose_name='Социальные сети')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
