# Generated by Django 3.2.6 on 2021-11-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
