# Generated by Django 3.2.9 on 2022-07-08 05:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Характеристики'),
            preserve_default=False,
        ),
    ]
