# Generated by Django 3.2.9 on 2022-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0003_product_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes_am',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes_eu',
        ),
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.JSONField(blank=True, verbose_name='Характеристики'),
        ),
    ]
