# Generated by Django 3.2.9 on 2022-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0005_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='type',
            field=models.CharField(choices=[('Число', 'number'), ('Текст', 'text')], default='text', max_length=6, verbose_name='Тип параметра'),
        ),
    ]
