# Generated by Django 3.2.9 on 2022-07-16 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0007_alter_parameters_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория для складчины', 'verbose_name_plural': 'Категории для складчины'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар для складчины', 'verbose_name_plural': 'Товары для складчины'},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=160, unique=True, verbose_name='URL'),
        ),
    ]
