# Generated by Django 3.2.9 on 2022-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0008_auto_20220716_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма в рублях', max_digits=10, verbose_name='Стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма в рублях', max_digits=8, verbose_name='Цена за единицу товара'),
        ),
    ]
