# Generated by Django 3.2.9 on 2022-07-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0013_auto_20220727_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Заказ отправлен'),
        ),
    ]
