# Generated by Django 3.2.9 on 2022-07-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220727_1507'),
        ('goods', '0009_alter_product_parameters'),
        ('potlucks', '0014_customerorder_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_number', models.PositiveSmallIntegerField(default=0, verbose_name='Доля пользователя в заказе')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('post_index', models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес доставки')),
                ('paid', models.BooleanField(default=False, verbose_name='Доля пользователя в заказе оплачена')),
                ('send', models.BooleanField(default=False, verbose_name='Заказ отправлен')),
                ('notes', models.TextField(blank=True, max_length=300, verbose_name='Примечание к заказу')),
                ('date_send', models.DateField(blank=True, default=None, null=True, verbose_name='Дата отправления')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Участник заказа')),
            ],
            options={
                'verbose_name': 'Доля пользователя',
                'verbose_name_plural': 'Доли пользователей',
            },
        ),
        migrations.CreateModel(
            name='Potluck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(default=0, verbose_name='Количество единиц товара в заказе')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Сумма в рублях', max_digits=8, verbose_name='Цена за единицу товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Сумма в рублях', max_digits=10, verbose_name='Стоимость заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_amass', models.DateTimeField(blank=True, null=True, verbose_name='Время заполнения')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('number_finished', models.PositiveSmallIntegerField(default=0, verbose_name='Завершено заказов такого же товара в таком же количестве')),
                ('amassed', models.BooleanField(default=False, verbose_name='Все позиции заказа забронированы')),
                ('paid', models.BooleanField(default=False, verbose_name='Заказ полностью оплачен')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potluck_creators', to='users.profile', verbose_name='Создатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potlucks', to='goods.product', verbose_name='Товар')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potluck_vendor', to='goods.vendor', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Складчина',
                'verbose_name_plural': 'Складчины',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='part',
            name='potluck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='potlucks.potluck', verbose_name='Заказ'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('potluck', 'customer')},
        ),
    ]
