# Generated by Django 3.2.9 on 2022-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0017_auto_20220728_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='confirmed_by_user',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='partorder',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден менеджером'),
        ),
    ]
