# Generated by Django 3.2.9 on 2022-07-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0018_auto_20220728_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potluck',
            name='url',
        ),
    ]
