# Generated by Django 3.2.9 on 2022-08-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0019_remove_potluck_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='vendors/', verbose_name='Логотип')),
                ('finished_potlucks', models.PositiveSmallIntegerField(default=0, verbose_name='Завершенные заказы')),
                ('contact_phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('contact_site', models.CharField(blank=True, max_length=50, verbose_name='Сайт')),
                ('contact_social', models.CharField(blank=True, max_length=200, verbose_name='Социальные сети')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterField(
            model_name='potluck',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potluck_vendor', to='potlucks.vendor', verbose_name='Поставщик'),
        ),
    ]
