# Generated by Django 3.2.9 on 2022-07-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0009_auto_20220717_1441'),
        ('retail', '0002_auto_20220717_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoretail',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_products_retail', to='potlucks.manufacturer', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
