# Generated by Django 3.2.9 on 2022-07-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0010_alter_product_manufacturer'),
        ('retail', '0005_remove_producttoretail_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttoretail',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_products_retail', to='potlucks.manufacturer', verbose_name='Производитель'),
        ),
    ]
