# Generated by Django 3.2.9 on 2022-07-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_producttoretail_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttoretail',
            name='manufacturer',
        ),
    ]
