# Generated by Django 3.2.9 on 2022-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0009_orderitem_ordertoretail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='post_index',
            field=models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс'),
        ),
    ]
