# Generated by Django 3.2.9 on 2022-07-18 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_auto_20220718_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertoretail',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, verbose_name='Адрес электронной почты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='ordertoretail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона'),
        ),
    ]
