# Generated by Django 3.2.9 on 2022-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_ordertoretail_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertoretail',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='ordertoretail',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
    ]
