# Generated by Django 3.2.9 on 2022-07-26 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0015_auto_20220720_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 9, 36, 27, 886104, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
