# Generated by Django 3.2.9 on 2022-07-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0016_orderitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_at',
        ),
    ]
