# Generated by Django 3.2.9 on 2022-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_alter_ordertoretail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoretail',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден менеджером'),
        ),
    ]
