# Generated by Django 3.2.9 on 2022-08-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220727_1507'),
        ('retail', '0019_alter_ordertoretail_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoretail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='users.profile', verbose_name='Заказчик'),
        ),
    ]
