# Generated by Django 3.2.9 on 2022-01-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220114_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сумма в рублях', verbose_name='Баланс счета'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='finished_orders',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Завершенные заказы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patrynomic',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_index',
            field=models.CharField(blank=True, max_length=6, verbose_name='Почтовый индекс'),
        ),
    ]
