# Generated by Django 3.2.9 on 2022-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220120_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patrynomic',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
