# Generated by Django 3.2.9 on 2022-01-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='patrynomic',
            new_name='patronymic',
        ),
    ]
