# Generated by Django 3.2.9 on 2022-07-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
    ]
