# Generated by Django 3.2.6 on 2021-11-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('potlucks', '0003_rename_title_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('strap_material', models.CharField(blank=True, max_length=10, verbose_name='Материал ремешка')),
                ('mechanism_type', models.CharField(blank=True, max_length=15, verbose_name='Тип механизма')),
                ('dial_size', models.CharField(blank=True, max_length=5, verbose_name='Размер циферблата, см')),
                ('dial_material', models.CharField(blank=True, max_length=10, verbose_name='Материал циферблата')),
                ('colors', models.CharField(blank=True, max_length=40, verbose_name='Линейка цветов')),
                ('categories', models.ManyToManyField(to='potlucks.Category', verbose_name='Категории')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='potlucks.manufacturer', verbose_name='Производитель')),
                ('vendors', models.ManyToManyField(to='potlucks.Vendor', verbose_name='Поставщики')),
            ],
            options={
                'verbose_name': 'Наручные часы',
                'verbose_name_plural': 'Наручные часы',
            },
        ),
        migrations.CreateModel(
            name='PantsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('sizes_eu', models.CharField(blank=True, max_length=10, verbose_name='Линейка европейских размеров')),
                ('sizes_am', models.CharField(blank=True, max_length=15, verbose_name='Линейка американских размеров')),
                ('colors', models.CharField(blank=True, max_length=40, verbose_name='Линейка цветов')),
                ('categories', models.ManyToManyField(to='potlucks.Category', verbose_name='Категории')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='potlucks.manufacturer', verbose_name='Производитель')),
                ('vendors', models.ManyToManyField(to='potlucks.Vendor', verbose_name='Поставщики')),
            ],
            options={
                'verbose_name': 'Штаны',
                'verbose_name_plural': 'Штаны',
            },
        ),
    ]
