# Generated by Django 3.2.9 on 2022-07-20 07:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='goods.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория для складчины',
                'verbose_name_plural': 'Категории для складчины',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='manufacturers/', verbose_name='Логотип')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('number', 'Число'), ('text', 'Текст')], default='text', help_text='Для числового параметра (например, размер, кол-во чего-либо) - число, для остальных - текст.', max_length=6, verbose_name='Тип параметра')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/product_images', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение товара',
                'verbose_name_plural': 'Дополнительные изображения товара',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='vendors/', verbose_name='Логотип')),
                ('finished_orders', models.PositiveSmallIntegerField(default=0, verbose_name='Завершенные заказы')),
                ('contact_phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона')),
                ('contact_site', models.CharField(blank=True, max_length=50, verbose_name='Сайт')),
                ('contact_social', models.CharField(blank=True, max_length=200, verbose_name='Социальные сети')),
                ('url', models.SlugField(max_length=160)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('parameters', models.JSONField(blank=True, verbose_name='Характеристики')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', models.TextField(blank=True, max_length=200, verbose_name='Тэги товара')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='URL')),
                ('available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('stock', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Сумма в рублях', max_digits=8, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='goods.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_products', to='goods.manufacturer', verbose_name='Производитель')),
                ('vendors', models.ManyToManyField(related_name='vendor_products', to='goods.Vendor', verbose_name='Поставщики')),
            ],
            options={
                'verbose_name': 'Товар для складчины',
                'verbose_name_plural': 'Товары для складчины',
            },
        ),
    ]
