# Generated by Django 3.2.9 on 2022-07-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20220722_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='goods.review', verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
