# Generated by Django 3.2.9 on 2022-07-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_instagram'),
        ('goods', '0005_rating_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-id',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'product')},
        ),
    ]
