# Generated by Django 3.2.9 on 2022-07-26 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20220725_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 9, 37, 26, 166239, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
