# Generated by Django 3.2.9 on 2022-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
