# Generated by Django 3.2.9 on 2022-07-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
    ]
