# Generated by Django 3.2.9 on 2022-08-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlucks', '0020_auto_20220805_1611'),
        ('goods', '0010_rename_finished_orders_vendor_finished_potlucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendors',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
